/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kaspareit.niklas.TestProject;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }


    public String getMel(){
        return "I love Mel";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(new App().getMel());
    }
}
