/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kaspareit.niklas.TestProject;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
        assertTrue("app returning incorrect greeting", classUnderTest.getGreeting().equals("Hello world."));
        assertTrue("app should say that niklas loves Melissa", classUnderTest.getMel().equals("I love Mel"));
    }
}
